export const API = 'http://localhost:7010';

export const provinciasConCiudades = {
  "Buenos Aires": ["La Plata", "Mar del Plata", "Bahía Blanca", "Tandil"],
  "CABA": ["Ciudad Autónoma de Buenos Aires"],
  "Catamarca": ["San Fernando del Valle de Catamarca", "Belén", "Tinogasta"],
  "Chaco": ["Resistencia", "Roque Sáenz Peña", "Villa Ángela"],
  "Chubut": ["Rawson", "Trelew", "Comodoro Rivadavia"],
  "Córdoba": ["Córdoba", "Villa Carlos Paz", "Río Cuarto", "Villa María"],
  "Corrientes": ["Corrientes", "Goya", "Paso de los Libres"],
  "Entre Ríos": ["Paraná", "Concordia", "Gualeguaychú"],
  "Formosa": ["Formosa", "Clorinda", "Pirané"],
  "Jujuy": ["San Salvador de Jujuy", "Palpalá", "Perico"],
  "La Pampa": ["Santa Rosa", "General Pico"],
  "La Rioja": ["La Rioja", "Chilecito"],
  "Mendoza": ["Mendoza", "San Rafael", "Godoy Cruz"],
  "Misiones": ["Posadas", "Oberá", "Eldorado"],
  "Neuquén": ["Neuquén", "San Martín de los Andes", "Cutral Có"],
  "Río Negro": ["Viedma", "Bariloche", "Cipolletti"],
  "Salta": ["Salta", "San Ramón de la Nueva Orán", "Tartagal"],
  "San Juan": ["San Juan", "Rawson", "Chimbas"],
  "San Luis": ["San Luis", "Villa Mercedes"],
  "Santa Cruz": ["Río Gallegos", "Caleta Olivia"],
  "Santa Fe": ["Santa Fe", "Rosario", "Rafaela"],
  "Santiago del Estero": ["Santiago del Estero", "La Banda"],
  "Tierra del Fuego": ["Ushuaia", "Río Grande"],
  "Tucumán": ["San Miguel de Tucumán", "Tafí Viejo", "Yerba Buena"],
};